const dbConfig = require("../config/db.config.js");
const mongoose = require("mongoose");
mongoose.Promise = global.Promise;
const db = {};
db.mongoose = mongoose;
db.url = dbConfig.url;
db.house = require("./houseModel.js")(mongoose);
db.review = require("./reviewModel")(mongoose);
module.exports = db;